modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="cahos"
version="1.1.0"
displayName="cahos"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Hedgehawk11"
description="oh boy"

[[dependencies.cahos]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




